# Generated by Django 3.2.9 on 2021-11-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('rut', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('nemo_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
