# Generated by Django 3.2.9 on 2021-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='operation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
