# Generated by Django 3.2.9 on 2021-11-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movimiento_operation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('rut', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
    ]
