# Generated by Django 3.2.9 on 2021-11-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_saldos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='operation_date',
            field=models.DateField(),
        ),
    ]
